### ISSUE TITLE
Kernel Freeze on Boot (Ubuntu 14.04)

### ISSUE THREAD

**Issue by Seablade** [raphael/linux-4.1-samus#23] opened 2015-07-29 14:59 UTC
Trying to load the Ubuntu kernel (Samus hardware obviously), either using the deb packages or building it from the tree following the instructions, it seems to install fine, but when I try to boot it gets to the text: "Loading initial ramdisk" and apparently freezes.  Ubuntu 14.04 LTS installed via chrubuntu scripts.

Not real sure what I can do to help with the troubleshooting at this point, any suggestions?  I have seen reports that it is working fine with 15.04, but the chrubuntu scripts don't handle that install very well, and I would prefer the LTS anyways personally if possible, but if I need to I will try to install 15.04 via thumb drive to the partition.

Thanks very much for the help, and for the work in putting this together.

**Comment by raphael** [comment] 2015-07-31 06:40
This sounds similar to issue #18. You should try @recri's generic config. Would be great if you could find which of the kernel config option(s) need tweaking!

**Comment by Seablade** [comment] 2015-07-31 07:06
Will give it a shot, one thing I noticed was that support for RAM disks were modular in your kernel, and built in with tsowell's and I suspect the generic, considering there are two options Ubuntu mentions having to have built in, you had one built in (INITRD) but not the other (RAM).  But that by itself did not fix it, and right now I am struggling to finish a few things up tonight by pulling an all nighter.  That being said I agree with your overall approach to the kernel, if this is for a specific hardware, no reason not to tune it to that hardware.

**Comment by Seablade** [comment] 2015-07-31 08:06
Well I didn't get that working either, but I am going to have to come back to it, I am not counting out it may just be sleep deprivation (Working on that while watching AMIs build that I am trying to wrap up before I leave).  Will come back to this.

**Comment by raphael** [comment] 2015-07-31 16:01
Thanks for looking into it.

**Comment by Seablade** [comment] 2015-08-02 18:23
Ok updates... I am in the process of moving Ubuntu off the internal to an external disk.  As a result I went back to the kernel mentioned there, and got it working after discovering that it was a different branch that had the config mentioned.  I will have to do more testing, but it isn't a perfect working system at this point, going to post more info in the thread for #18 to keep troubleshooting there as it directly relates to that kernel config I think.

**Comment by raphael** [comment] 2015-08-03 02:35
Closing this issue as duplicate of #18.

**Closed by raphael** 2015-08-03 02:35 UTC
