### ISSUE TITLE
Headphone volume too low?

### ISSUE THREAD

**Issue by defunkt1721** [raphael/linux-4.1-samus#19] opened 2015-07-24 23:21 UTC
Hi,

I'm not sure if this is an issue or not but I'm experiencing rather low volume when outputting sound through headphones even when pushing it beyond 100%. I'm running Antergos with Gnome 3.16. 

Do you reckon there's anything that can be done to make the sound output louder? 

Cheers

**Comment by Ivan0xFF** [comment] 2015-07-24 23:48
I have noticed this as well. It's extremely low, even at the highest possible volume.

**Comment by raphael** [comment] 2015-07-25 00:04
Have you checked the volume with `alsamixer`, something like `alsamixer -c 0` should open it with the broadwell sound card selected. Check the master volume there and the second setting `Headphon` (use `m` to turn it off or on).

**Comment by defunkt1721** [comment] 2015-07-26 10:56
I did mess around with alsamixer as you suggested a little bit but everything seems to be alright there. I'll poke around some more and report if I find anything.

**Comment by raphael** [comment] 2015-07-26 22:51
Thanks, I'm wondering: are you able to try it under ChromeOS and does it work better there?

**Comment by defunkt1721** [comment] 2015-07-27 08:06
Unfortunately, I am not as I've wiped ChromeOS. 

How's the headphone volume for you, is it fine? Maybe I should just try with different headphones and see.

**Comment by recri** [comment] 2015-07-27 21:38
I pulled a copy of /usr/share/alsa off chromeos-dev on my pixel a day or two ago, and the bdw-rt5677 files had the following diff against linux-4.1-samus/scripts/setup/ucm

```
rec@elf2015:~$ diff -r  ~/Projects/from-samus/usr-share-alsa/ucm/bdw-rt5677/ ~/Projects/linux-4.1-samus/scripts/setup/ucm/bdw-rt5677/
diff -r /home/rec/Projects/from-samus/usr-share-alsa/ucm/bdw-rt5677/bdw-rt5677.conf /home/rec/Projects/linux-4.1-samus/scripts/setup/ucm/bdw-rt5677/bdw-rt5677.conf
2d1
< 
diff -r /home/rec/Projects/from-samus/usr-share-alsa/ucm/bdw-rt5677/HiFi.conf /home/rec/Projects/linux-4.1-samus/scripts/setup/ucm/bdw-rt5677/HiFi.conf
13c13
< 		cset "name='Master Playback Volume' 30"
---
> 		cset "name='Master Playback Volume' 26"
58c58
< 		cset "name='ADC1 Capture Volume' 31"
---
> 		cset "name='ADC1 Capture Volume' 63"
63,72d62
< 
< 		cset "name='Remote DMICs Switch' on"
< 		cset "name='Mono DMIC L Mux' DMIC1"
< 		cset "name='Mono ADC2 L Mux' DMIC"
< 		cset "name='Mono ADC MIXL ADC1 Switch' off"
< 		cset "name='Mono ADC MIXL ADC2 Switch' on"
< 		cset "name='VAD ADC Mux' MONO ADC MIX L"
< 		cset "name='IB01 Mux' VAD ADC/DAC1 FS"
< 		cset "name='IB01 Bypass Mux' Bypass"
< 		cset "name='Mono ADC Boost Volume' 2"
120a111
> 		cset "name='Remote DMICs Switch' off"
140a132
> 		cset "name='Remote DMICs Switch' on"
```

Redoing
```
 ALSA_CONFIG_UCM=ucm/ alsaucm -c bdw-rt5677 set _verb HiFi
```
with the new files with the new files immediately improved my microphone response enough that I can talk to duolingo in chrome for the first time on linux.  Maybe the other settings will help the headphones?  I'll push the newer files to my repo.

**Comment by raphael** [comment] 2015-07-28 03:32
Nice! thanks for sharing. Would you mind creating a PR and I'll apply the changes? I had taken the oiriginal file from the ChromeOS tree but I guess something else must be updating the values there.

**Comment by defunkt1721** [comment] 2015-07-28 16:39
That's awesome! Thanks for pulling the files from ChromeOS. Linux on the Pixel is looking better by the day :dancer:

**Comment by recri** [comment] 2015-07-28 19:37
You should have a pull request.  

Note that both the audio input and output channels lose some gain in this version of HiFi.conf, though the microphone may be picking up some gain in the other part of the patch.  I found the headphone output okay with this patch, but it's pretty hard to figure out who stepped on the mixer settings last.

**Comment by raphael** [comment] 2015-07-28 21:31
Thanks! PR #22 is merged. @defunkt1721 @Ivan0xFF can you confirm whether these settings improve headphones volume?

**Comment by Ivan0xFF** [comment] 2015-07-29 20:18
The issue is still there on the latest kernel with the new ALSA Config. The volume is very low and the channels are reversed(left is right, right is left).

**Comment by raphael** [comment] 2015-07-29 22:01
just to confirm: that's after re-running `ucm` with the new config as well?

**Comment by Ivan0xFF** [comment] 2015-07-30 20:37
That is correct.

**Comment by nskaggs** [comment] 2015-08-10 14:40
Just adding some confirmation for @defunkt1721. It's not just you, I too have extremely low volume in the headphone slot. Bumping the audio in obvious (alsamixer) and non-obvious ways (system global pre-amp) didn't help. It will distort if pushed too much further; clearly something isn't quite right.

**Comment by defunkt1721** [comment] 2015-08-10 18:48
Glad to know I'm not the only one experiencing this. 

Can also confirm that with latest release left and right channels are reversed. Even with volume boosted past 100%, audio levels are low.

**Comment by raphael** [comment] 2015-08-11 03:50
I gave this another shot and used `alsactl` to capture the alsa state in a chroot running under the ChromeOS kernel. I then restored the state under the 4.1 samus kernel and it seemed to work: I'm listening to music via headphones now, the channels are not reversed and the volume seems OK. Please give it a shot, get the latest master and run:
```bash
cd scripts/setup
sudo alsactl restore --file alsa/asound.state
```
I've also update the `sound.sh` script to do this automatically.

**Comment by Ivan0xFF** [comment] 2015-08-11 05:21
That seems to have fixed it for me! Thanks for all the great work with getting this wonderful laptop working flawlessly on Linux, @raphael !

**Comment by raphael** [comment] 2015-08-11 05:37
np, glad it's working!

**Closed by raphael** 2015-08-11 05:37 UTC
